# Generated by Django 3.2.25 on 2024-11-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_book_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uid',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
